export const mockTrackers = [
  { category: "Entertainment", limit: 1000, interval: "week" },
  { category: "Food and Drink", limit: 100, interval: "month" },
];

export function getCategories() {
  const categoriesSet = new Set();
  mockData.transactions.forEach((transaction) => {
    transaction.category.forEach((category) => {
      categoriesSet.add(category);
    });
  });
  return [...categoriesSet];
}

export const mockData = {
  accounts: [
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      balances: {
        available: 110.94,
        current: 110.94,
        iso_currency_code: "USD",
        unofficial_currency_code: null,
      },
      mask: "0000",
      name: "Plaid Checking",
      official_name: "Plaid Gold Standard 0% Interest Checking",
      subtype: "checking",
      type: "depository",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      balances: {
        available: 2050.75,
        current: 2050.75,
        iso_currency_code: "USD",
        unofficial_currency_code: null,
      },
      mask: "0011",
      name: "Plaid Savings",
      official_name: "Plaid Silver 1.5% Interest Savings",
      subtype: "savings",
      type: "depository",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      balances: {
        available: 525.6,
        current: 525.6,
        iso_currency_code: "USD",
        unofficial_currency_code: null,
      },
      mask: "0022",
      name: "Plaid Credit",
      official_name: "Plaid Platinum Standard 20% APR Credit Card",
      subtype: "credit card",
      type: "credit",
    },
  ],
  transactions: [
    // Transactions for account 1 (Checking)
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 28.34,
      iso_currency_code: "USD",
      category: ["Food and Drink", "Restaurants", "Fast Food"],
      date: "2023-09-28",
      name: "Dd Doordash Burgerkin",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 72.1,
      iso_currency_code: "USD",
      category: ["Shops", "Supermarkets and Groceries"],
      date: "2023-09-24",
      name: "PURCHASE WM SUPERCENTER #1700",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 15.5,
      iso_currency_code: "USD",
      category: ["Entertainment", "Movies"],
      date: "2023-09-22",
      name: "Netflix Subscription",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 30.2,
      iso_currency_code: "USD",
      category: ["Personal Care", "Pharmacy"],
      date: "2023-09-20",
      name: "CVS Pharmacy",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 60.0,
      iso_currency_code: "USD",
      category: ["Transportation", "Gas Stations"],
      date: "2023-09-18",
      name: "Shell Gas Station",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 45.0,
      iso_currency_code: "USD",
      category: ["Travel", "Airlines and Aviation Services"],
      date: "2023-09-16",
      name: "United Airlines",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 12.75,
      iso_currency_code: "USD",
      category: ["Service", "Telecommunication Services"],
      date: "2023-09-14",
      name: "Verizon Wireless",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 1000.99,
      iso_currency_code: "USD",
      category: ["Entertainment", "Video Game Arcades"],
      date: "2023-09-12",
      name: "Steam Games",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 13.5,
      iso_currency_code: "USD",
      category: ["Food and Drink", "Bakeries"],
      date: "2023-09-10",
      name: "Starbucks",
    },
    {
      account_id: "BxBXxLj1m4HMXBm9WZZmCWVbPjX16EHwv99vp",
      amount: 7.25,
      iso_currency_code: "USD",
      category: ["Recreation", "Gyms and Fitness Centers"],
      date: "2023-09-08",
      name: "Gym Membership",
    },
    // Transactions for account 2 (Savings)
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 120.0,
      iso_currency_code: "USD",
      category: ["Food and Drink", "Restaurants"],
      date: "2023-09-07",
      name: "Cheesecake Factory",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 50.0,
      iso_currency_code: "USD",
      category: ["Entertainment", "Music"],
      date: "2023-09-09",
      name: "Spotify Premium",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 13.99,
      iso_currency_code: "USD",
      category: ["Personal Care", "Beauty Supplies"],
      date: "2023-09-11",
      name: "Bath & Body Works",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 25.75,
      iso_currency_code: "USD",
      category: ["Transportation", "Taxis and Rideshares"],
      date: "2023-09-13",
      name: "Uber Ride",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 32.5,
      iso_currency_code: "USD",
      category: ["Shops", "Clothing and Accessories"],
      date: "2023-09-15",
      name: "Uniqlo Purchase",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 87.9,
      iso_currency_code: "USD",
      category: ["General Merchandise"],
      date: "2023-09-17",
      name: "Amazon Order",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 14.99,
      iso_currency_code: "USD",
      category: ["Service", "Subscription Services"],
      date: "2023-09-19",
      name: "Apple iCloud Storage",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 29.95,
      iso_currency_code: "USD",
      category: ["Recreation", "Arts and Crafts"],
      date: "2023-09-21",
      name: "Michaels Stores",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 75.0,
      iso_currency_code: "USD",
      category: ["Travel", "Airline"],
      date: "2023-09-23",
      name: "Southwest Airlines",
    },
    {
      account_id: "AC2nd0j2D4HSdXmpLZZ2CWVbKjX12EHwv22kp",
      amount: 20.0,
      iso_currency_code: "USD",
      category: ["Food and Drink", "Coffee Shop"],
      date: "2023-09-25",
      name: "Starbucks",
    },
    // Transactions for account 3 (Credit)
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 215.0,
      iso_currency_code: "USD",
      category: ["General Merchandise", "Electronics"],
      date: "2023-09-06",
      name: "Apple Store",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 45.5,
      iso_currency_code: "USD",
      category: ["Entertainment", "Theaters"],
      date: "2023-09-08",
      name: "AMC Theatres",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 34.9,
      iso_currency_code: "USD",
      category: ["Food and Drink", "Bars"],
      date: "2023-09-10",
      name: "Local Bar",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 68.25,
      iso_currency_code: "USD",
      category: ["Personal Care", "Spas and Salons"],
      date: "2023-09-12",
      name: "Green Spa",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 23.6,
      iso_currency_code: "USD",
      category: ["Transportation", "Public Transportation"],
      date: "2023-09-14",
      name: "City Metro Pass",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 150.0,
      iso_currency_code: "USD",
      category: ["Shops", "Home Improvement"],
      date: "2023-09-16",
      name: "Home Depot",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 89.99,
      iso_currency_code: "USD",
      category: ["Service", "Internet Services"],
      date: "2023-09-18",
      name: "Comcast Xfinity",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 19.99,
      iso_currency_code: "USD",
      category: ["Recreation", "Movies and DVDs"],
      date: "2023-09-20",
      name: "Netflix Monthly Subscription",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 120.0,
      iso_currency_code: "USD",
      category: ["Travel", "Hotels"],
      date: "2023-09-22",
      name: "Holiday Inn Express",
    },
    {
      account_id: "BC3rd3k3E5HTeYnpMZZ3CWUbLjX13FHwv33lq",
      amount: 55.0,
      iso_currency_code: "USD",
      category: ["Food and Drink", "Restaurants", "Italian"],
      date: "2023-09-24",
      name: "Mario's Pizzeria",
    },
  ],
  item: {
    available_products: ["balance", "identity", "investments"],
    billed_products: ["assets", "auth", "liabilities", "transactions"],
    consent_expiration_time: null,
    error: null,
    institution_id: "ins_3",
    item_id: "eVBnVMp7zdTJLkRNr33Rs6zr7KNJqBFL9DrE6",
    update_type: "background",
    webhook: "https://www.genericwebhookurl.com/webhook",
  },
  total_transactions: 30,
  request_id: "45QSn",
};
