import "~/styles/globals.css";
import "./super.css";
import Providers from "./providers";
import { Inter } from "next/font/google";
import { SideMenu } from "./sideMenu";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "John Tran Empower Take Home",
  description: "Generated by John Tran",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <div className="container">
          <SideMenu />
          <Providers>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
